### ISSUE TITLE
Will it support hatch 100?

### ISSUE THREAD

**Issue by midozalouk** [newbit1/rootCROS#3]
I have a few questions not issues indeed!
1- will it work on other recoveries like hatch?
2- will it stays if I updated the recovery or chromeos - if I updated the rammus 93 etc..... -

Thanks sir 😊

**Comment by windowz414** [comment]
> I have a few questions not issues indeed! 1- will it work on other recoveries like hatch? 2- will it stays if I updated the recovery or chromeos - if I updated the rammus 93 etc..... -
> 
> Thanks sir 😊

I personally think it's not dependant on your recovery image but rather the Android support status (Also known as "Play Store support"). So if Play Store is supported and you enabled it, you can use this.

For recovery, it doesn't stay even throughout OTA updates so I guess it's the same case on updates with recovery images as well.

**Comment by midozalouk** [comment]
How to check if my play store is supported?

**Comment by midozalouk** [comment]
I already have playstore

when i run the command it throw this error

````
Could not open /opt/google/containers/android/system.raw.img, because No such file or directory
Make your changes and Enter when finshed to continue
[*] Patching Overlay with fake ramdisk.img
stat: cannot statx '/usr/local/crosswork/fin/system': No such file or directory
[-] Extracting ramdisk.cpio
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
chown: unknown user/group 0755:u:object_r:magisk_exec:s0
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
        -c      List changed files
        -v      Verbose
        -f      Hide errors
chown: unknown user/group 0755:u:object_r:magisk_exec:s0
chown: unknown user/group 0755:u:object_r:system_file:s0
chown: unknown user/group 0755:u:object_r:system_file:s0
chown: unknown user/group 0755:u:object_r:system_file:s0
chown: unknown user/group 0755:u:object_r:system_file:s0
chown: unknown user/group 0755:u:object_r:system_file:s0
chown: unknown user/group 0755:u:object_r:system_file:s0
chown: unknown user/group 0755:u:object_r:magisk_file:s0
[*] Injecting Magisk into init.rc
[*] create Backup File of /etc/selinux/arc/policy/policy.30
[*] Inject SELinux with Magisk built-in rules via ADB
fopen: /sys/fs/selinux/policy failed with 13: Permission denied
adb: error: failed to stat remote object '/data/data/com.android.shell/Magisk/policy.30.magisk': No such file or directory
/data/data/com.android.shell/Magisk/sepolicy.magisk: 1 file pulled. 91.5 MB/s (729994 bytes in 0.008s)
[!] Set Permissions and Context from
[-] /etc/selinux/arc/contexts/files/file_contexts to /etc/selinux/arc/policy/policy.30
[*] Change Owner:Group to 0:0
chown: cannot access '/etc/selinux/arc/policy/policy.30': No such file or directory
[-] Change Mod to 0644
chmod: cannot access '/etc/selinux/arc/policy/policy.30': No such file or directory
[*] Change Context to u:object_r:cros_selinux_config_file:s0
chcon: cannot access '/etc/selinux/arc/policy/policy.30': No such file or directory
[!] Set Permissions and Context from
[-] /usr/local/crosswork/fin/sepolicy to /usr/local/crosswork/fin/sepolicy.magisk
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
[*] Change Owner:Group to :
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
[-] Change Mod to 
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
chmod: missing operand after '/usr/local/crosswork/fin/sepolicy.magisk'
Try 'chmod --help' for more information.
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
[*] Change Context to 
chcon: failed to get security context of '/usr/local/crosswork/fin/sepolicy': No such file or directory
[*] create Backup File of /opt/google/containers/android/system.raw.img
mv: cannot stat '/opt/google/containers/android/system.raw.img': No such file or directory
[-] Generating SquashFS with Magisk
rm: cannot remove '/opt/google/containers/android/system.raw.img': No such file or directory
Could not create destination file: No such file or directory
[*] Set Magisk SquashFS System
stat: cannot statx '/opt/google/containers/android/vendor.raw.img': No such file or directory
[*] Change Context to 
chcon: failed to get security context of '/opt/google/containers/android/vendor.raw.img': No such file or directory
[*] cleaning up /usr/local/crosswork/fin
``` 


what should i do ?

**Comment by windowz414** [comment]
> I already have playstore
> 
> when i run the command it throw this error
> 
> ```
> Could not open /opt/google/containers/android/system.raw.img, because No such file or directory
> Make your changes and Enter when finshed to continue
> [*] Patching Overlay with fake ramdisk.img
> stat: cannot statx '/usr/local/crosswork/fin/system': No such file or directory
> [-] Extracting ramdisk.cpio
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> chown: unknown user/group 0755:u:object_r:magisk_exec:s0
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> BusyBox v1.34.1-Magisk (2022-01-25 03:29:40 PST) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
>         -R      Recurse
>         -c      List changed files
>         -v      Verbose
>         -f      Hide errors
> chown: unknown user/group 0755:u:object_r:magisk_exec:s0
> chown: unknown user/group 0755:u:object_r:system_file:s0
> chown: unknown user/group 0755:u:object_r:system_file:s0
> chown: unknown user/group 0755:u:object_r:system_file:s0
> chown: unknown user/group 0755:u:object_r:system_file:s0
> chown: unknown user/group 0755:u:object_r:system_file:s0
> chown: unknown user/group 0755:u:object_r:system_file:s0
> chown: unknown user/group 0755:u:object_r:magisk_file:s0
> [*] Injecting Magisk into init.rc
> [*] create Backup File of /etc/selinux/arc/policy/policy.30
> [*] Inject SELinux with Magisk built-in rules via ADB
> fopen: /sys/fs/selinux/policy failed with 13: Permission denied
> adb: error: failed to stat remote object '/data/data/com.android.shell/Magisk/policy.30.magisk': No such file or directory
> /data/data/com.android.shell/Magisk/sepolicy.magisk: 1 file pulled. 91.5 MB/s (729994 bytes in 0.008s)
> [!] Set Permissions and Context from
> [-] /etc/selinux/arc/contexts/files/file_contexts to /etc/selinux/arc/policy/policy.30
> [*] Change Owner:Group to 0:0
> chown: cannot access '/etc/selinux/arc/policy/policy.30': No such file or directory
> [-] Change Mod to 0644
> chmod: cannot access '/etc/selinux/arc/policy/policy.30': No such file or directory
> [*] Change Context to u:object_r:cros_selinux_config_file:s0
> chcon: cannot access '/etc/selinux/arc/policy/policy.30': No such file or directory
> [!] Set Permissions and Context from
> [-] /usr/local/crosswork/fin/sepolicy to /usr/local/crosswork/fin/sepolicy.magisk
> stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
> stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
> [*] Change Owner:Group to :
> stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
> stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
> stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
> [-] Change Mod to 
> stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
> chmod: missing operand after '/usr/local/crosswork/fin/sepolicy.magisk'
> Try 'chmod --help' for more information.
> stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
> [*] Change Context to 
> chcon: failed to get security context of '/usr/local/crosswork/fin/sepolicy': No such file or directory
> [*] create Backup File of /opt/google/containers/android/system.raw.img
> mv: cannot stat '/opt/google/containers/android/system.raw.img': No such file or directory
> [-] Generating SquashFS with Magisk
> rm: cannot remove '/opt/google/containers/android/system.raw.img': No such file or directory
> Could not create destination file: No such file or directory
> [*] Set Magisk SquashFS System
> stat: cannot statx '/opt/google/containers/android/vendor.raw.img': No such file or directory
> [*] Change Context to 
> chcon: failed to get security context of '/opt/google/containers/android/vendor.raw.img': No such file or directory
> [*] cleaning up /usr/local/crosswork/fin
> ``` 
> 
> 
> what should i do ?
> ```

Did you enable and launch Play Store for the first time? If so, can you send the output of `ls /opt/google/containers/android`?

**Comment by midozalouk** [comment]
`ls: cannot access '/opt/google/containers/android': No such file or directory`
but i have found a different folder for system.raw.img and edited the script as follows

```
SYSRAWIMG=/opt/google/vms/android/system.raw.img
VENRAWIMG=/opt/google/vms/android/vendor.raw.img
```

but i can't find `
/opt/google/containers/android/rootfs/root`


I am using android 11 with hatch recovery image

**Comment by midozalouk** [comment]
it through that error when i use the edited script 
```

[-] Moving to the location /usr/local/crosswork
[*] Deleting busybox from script ...
PWD=/usr/local/crosswork
[-] rootAVD.sh already there
[*] Magisk.zip already there
[-] busybox already there
[*] Init ADB
[*] Creating fake ramdisk.img
cp: cannot stat '/opt/google/containers/android/rootfs/root/init': No such file or directory
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
rootAVD.sh: 1 file pushed. 67.4 MB/s (7847625 bytes in 0.111s)
ramdisk.img: 1 file pushed. 0.0 MB/s (84 bytes in 0.043s)
Magisk.zip: 1 file pushed. 29.6 MB/s (10641074 bytes in 0.342s)
[!] We are in a bertha emulator shell
[-] Api Level Arch Detect
[-] Device Platform: x64
[-] ARCH32 x86
[-] Device SDK API: 30
[-] First API Level: 28
[-] Switch to the location of the script file
[*] Extracting busybox and Magisk.zip ...
[-] Checking AVDs Internet connection...
[!] AVD is online
[!] Checking available Magisk Versions
[?] Choose a Magisk Version to install and make it local
[!] (s)how all available Magisk Versions
[1] local stable '24.1' (ENTER)
[2] stable 24.3
[3] canary 42e5f515(24308)
[4] alpha 71e9c044-alpha(24308)
1 
[-] You choose Magisk stable Version '24.1'
[*] Re-Run rootAVD in Magisk Busybox STANDALONE (D)ASH
[-] We are now in Magisk Busybox STANDALONE (D)ASH
[*] rootAVD with Magisk '24.1' Installer
[-] Get Flags
[*] System-as-root, keep dm/avb-verity
[-] Encrypted data, keep forceencrypt
[*] RECOVERYMODE=false
[-] KEEPVERITY=true
[*] KEEPFORCEENCRYPT=true
[*] copy x86 files to /data/data/com.android.shell/Magisk/lib/x86_64
[-] copy all x86_64 files from /data/data/com.android.shell/Magisk/lib/x86_64 to /data/data/com.android.shell/Magisk
[*] Detecting ramdisk.img compression
[!] Ramdisk.img uses gzip compression
[-] taken from shakalaca's MagiskOnEmulator/process.sh
[*] executing ramdisk splitting / extraction / repacking
[-] API level greater then 30
[*] Check if we need to repack ramdisk before patching ..
[*] After decompressing ramdisk.img, magiskboot will work
Detected format: [gzip]
[-] Test patch status and do restore
[-] Checking ramdisk status
[-] STATUS=0
[-] Stock boot image detected
[-] Patching ramdisk
[*] adding overlay.d/sbin folders to ramdisk
Loading cpio: [ramdisk.cpio]
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Dump cpio: [ramdisk.cpio]
[!] PATCHFSTAB=false
[!] Skipping fstab.ranchu patch with /dev/block/sda
[?] If you want fstab.ranchu patched, Call rootAVD with PATCHFSTAB
[!] AddRCscripts=false
[!] Skip adding *.rc scripts into ramdisk.img/sbin/*.rc
[?] If you want *.rc scripts added into ramdisk.img/sbin/*.rc, Call rootAVD with AddRCscripts
[!] patching the ramdisk with Magisk Init
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Record new entry: [init] -> [.backup/.rmlist]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
[*] repacking back to ramdisk.img format
[!] Rename Magisk.zip to Magisk.apk
/data/data/com.android.shell/Magisk/ramdiskpatched4AVD.img: 1 file pulled. 5.3 MB/s (520475 bytes in 0.093s)
/data/data/com.android.shell/Magisk/Magisk.apk: 1 file pulled. 14.1 MB/s (10641074 bytes in 0.719s)
/data/data/com.android.shell/Magisk/busybox: 1 file pulled. 10.6 MB/s (2214088 bytes in 0.199s)
[*] Trying to install Magisk.apk
Success
[*] cleaning up /usr/local/crosswork/fin
Filesystem uses lz4 compression, this is unsupported by this version
Decompressors available:
        gzip
Make your changes and Enter when finshed to continue^C
```

it has something to do with the compression of the new system.raw.img

**Comment by windowz414** [comment]
> I am using android 11 with hatch recovery image

Thank you for FINALLY giving the information needed. The issue is Google is using a different style for Android environment at 11. And so it's not going to work. Either use a recovery with Android 9 as runtime or just try to cope with rootless ARC until the developer brings support for it.

**Comment by midozalouk** [comment]
Thanks sir :)
i will not be able to use it even if i successfully decompressed the system.raw.img 

am i right ?

**Comment by windowz414** [comment]
> Thanks sir :) i will not be able to use it even if i successfully decompressed the system.raw.img
> 
> am i right ?

You can, but won't work out too properly honestly...

**Comment by midozalouk** [comment]
thanks sir :)
hope for a clue for android 11

**Comment by newbit1** [comment]
> `ls: cannot access '/opt/google/containers/android': No such file or directory` but i have found a different folder for system.raw.img and edited the script as follows
> 
> ```
> SYSRAWIMG=/opt/google/vms/android/system.raw.img
> VENRAWIMG=/opt/google/vms/android/vendor.raw.img
> ```
> 
> but i can't find ` /opt/google/containers/android/rootfs/root`
> 
> I am using android 11 with hatch recovery image

What makes you think it is Android 11?
In the script it even says it is  First API Level: 28 -> PIE

**Comment by midozalouk** [comment]
I didn't get your response
I have android 11 as stated by Google play itself

**Comment by windowz414** [comment]
> [snip] In the script it even says it is First API Level: 28 -> PIE

@newbit1, but have you also seen that the directory script originally looks for without modification doesn't exist? So you shouldn't look for first API level, which states the Android API level **that board was first introduced** rather than **currently installed environment** from what I assume. Besides, even if that's not the case, data/filesystem structure migration is always a thing during upgrades. ;)
