### ISSUE TITLE
How about volteer or magisk v25.2 ?

### ISSUE THREAD

**Issue by 1457384613gh** [newbit1/rootCROS#4]
Could it work on `volteer` with `magisk v25.2` ?
![image](https://user-images.githubusercontent.com/69227436/169629254-3f63da77-269f-41e9-8971-a8d3ff15b05f.png)

**Comment by windowz414** [comment]
I'm not the developer of this, but I guess this should work on Brunchbooks regardless of recovery.

For Magisk 24.3 though, it all depends on TopJohnWu's changes. There hasn't been a change on installation style yet, so I presume it should install properly **if you have Android 9 environment**. This project doesn't seem to support Android 11 environment (see #3) due to Google's changes for it. So the only thing that would cause problems would be Android version you have present on the Brunchbook rather than the recovery or Magisk version until a change happens on Magisk side.

**Comment by newbit1** [comment]
You can place every Magisk.zip version you want in the directory, and see what happens. As @windowz414 already said,
as long as the structure of Magisk remains the same, it should work.

I 've just noticed some days ago, that there is new Android Version for ChromeOS out, finally. I will have a look into this to adapt the script accordingly.

ChromOS Versions differ sometimes, also I am not sure I my machine can run the volteer version. I will try it and give you feedback.

**Comment by newbit1** [comment]
It seems the 100 Version is still Android 9.

**Comment by 1457384613gh** [comment]
But mine has been android 11 before getting r101.
I remember that I have found that it has been android 11 since I installed r98.

![Screenshot 2022-05-25 08 49 13](https://user-images.githubusercontent.com/69227436/170157224-76c1e733-ebbd-4190-8fb4-f5c2fa8587e5.png)
![Screenshot 2022-05-25 08 49 32](https://user-images.githubusercontent.com/69227436/170157230-193cdb72-615d-4393-9749-d9a773450012.png)
![Screenshot 2022-05-25 08 54 28](https://user-images.githubusercontent.com/69227436/170157234-b371be01-3b3f-4c2e-86e2-992b4e0506f7.png)
![Screenshot 2022-05-25 09 08 42](https://user-images.githubusercontent.com/69227436/170157240-2837ec5b-9012-4dc9-b73b-d01bd22b35fb.png)
![Screenshot 2022-05-25 09 15 37](https://user-images.githubusercontent.com/69227436/170157839-b0e9ed2a-9edb-49c3-b716-01d66a342175.png)
![Screenshot 2022-05-25 09 18 44](https://user-images.githubusercontent.com/69227436/170158109-c3fc0521-9877-41eb-b006-11f95e145471.png)

**Comment by windowz414** [comment]
> But mine has been android 11 before getting r101. I remember that I have found that it has been android 11 since I installed r98.
Have you done some special change to get it or did you get it in official ways A.K.A. via OTA? How did you get it?

**Comment by 1457384613gh** [comment]
Emm…
The fact for me, that you haven't gotten Android 11 is as surprising as the fact for you, that I have gotten Android 11.

Would you like to try to close google play store and open again by using settings of ChromeOS ?

In short, to re-install android might give you an android 11.

**Comment by windowz414** [comment]
> Emm… The fact for me, that you haven't gotten Android 11 is as surprising as the fact for you, that I have gotten Android 11.
> 
> Would you like to try to close google play store and open again by using settings of ChromeOS ?
> 
> In short, to re-install android might give you an android 11.

Well, I can't use Volteer on my side though, I'm a poor girl being stuck at Rammus and Grunt and those 2 still didn't officially get Android 11 AFAIK.

@newbit1, can you try doing what @1457384613gh said here if you can use Volteer recovery and confirm it working or not? This goes over me now. XD

**Comment by 1457384613gh** [comment]
If your Intel cpu is 8th～9th gen, you could try `hatch`.

You are not a poor girl.
You are a girl who knows more than others in a way.

**Comment by 1457384613gh** [comment]
> > If your Intel cpu is 8th～9th gen, you could try `hatch`.
> 
> Missed by only one generation AAAAAAA! The CPU on my Intel machine is 7th gen - Intel Atom BayTrail Z3735F.

Try hatch! Make an .img of 16 GB for test.
Maybe a miracle will happen.

**Comment by 1457384613gh** [comment]
I'm sorry but I have seen it just now.
Sure！

**Comment by windowz414** [comment]
Update on this: Android 11+ devices still can't get rootCROS installed due to the new image format. This can be a real deal breaker when serious concerns, such as ability to restore from another device using root solutions such as Swift Backup, comes into play.

**Comment by a0910115172** [comment]
Is there any news about this?

Also, I notice that surface touch driver is included after r103 version:
https://github.com/sebanc/brunch/issues/1573

Really want to know if there is an update on volteer with r103+ version.

**Comment by windowz414** [comment]
> Is there any news about this?
> 
> Also, I notice that surface touch driver is included after r103 version:
> https://github.com/sebanc/brunch/issues/1573
> 
> Really want to know if there is an update on volteer with r103+ version.

Seems not. The script still supports just Android 9 ARC and not ARCVM (Android 11+). :/
