### ISSUE TITLE
For pie, How to run adb or run script again? 

### ISSUE THREAD

**Issue by 1457384613gh** [newbit1/rootCROS#6]
![image](https://user-images.githubusercontent.com/69227436/205479634-b6ae4a5b-c966-4a12-9d02-bab1f4c01bd7.png)

Could you tell me how to do next?

**Comment by 1457384613gh** [comment]
![image](https://user-images.githubusercontent.com/69227436/205484273-6fd398f4-76da-4c83-bec2-329010f66eb7.png)

`command not found`

I wonder if  to `crew install adb`

Where to `sudo adb start-server`?
By `crosh shell` or `debian container`?

**Comment by 1457384613gh** [comment]
OK, I've got it.
It's because of [chromeos-adb](https://github.com/nathanchance/chromeos-adb-fastboot) .

**Comment by 1457384613gh** [comment]
OK, I've got it.
It's because of [chromeos-adb] <https://github.com/nathanchance/chromeos-adb-fastboot> .

**Comment by 1457384613gh** [comment]
But it is like what is an Android Phone with Magisk not entering its Launcher and always rebooting.

My old phone is Redmi Note 5 (whyred) with Android Pie. 
Once, it updated Magisk to one version of 25, only to reboot over and over again but not to enter its Laucher.

So, I think there is a bug with 25 and pie.

It cannot start the Android Container after bash-ing.

Could you add a Magisk Module for fear that and LSPosed by expanding your script ?

All in all, it would have been a script for busybox + Magisk + LSPosed + Module for fear that .

**Comment by 1457384613gh** [comment]
Like [initrd-magisk](https://github.com/HuskyDG/initrd-magisk), could your script mount a DIY boot-magisk.img as boot partition of Android Container?

It is convenient for users to update magisk.

I've seen ramdisk.img in your script, so I think you can do it.

Edit scripts to make Android Container mount DIY boot-magisk.img as /dev/block/loopX, as boot partition.

**Comment by 1457384613gh** [comment]
![image](https://user-images.githubusercontent.com/69227436/205493545-c8a3e8df-9c1d-4e6a-8207-18c5dba2bf69.png)

libc: Found user/group name 'netperf' in '/etc/group' without required prefix 'system_'
libc: Found user/group name 'tcpdump' in '/etc/group' without required prefix 'system_'
chown: unknown user/group 0755:u:object_r:magisk_file:s0
[*] Injecting Magisk into init.rc
[-] /etc/selinux/arc/policy/policy.30 Backup exists already
[*] Inject SELinux with Magisk built-in rules via ADB
adb: error: failed to stat remote object '/data/data/com.android.shell/Magisk/policy.30.magisk': No such file or directory
adb: error: failed to stat remote object '/data/data/com.android.shell/Magisk/sepolicy.magisk': No such file or directory
[!] Set Permissions and Context from
[-] /etc/selinux/arc/contexts/files/file_contexts to /etc/selinux/arc/policy/policy.30
[*] Change Owner:Group to 0:0
chown: cannot access '/etc/selinux/arc/policy/policy.30': No such file or directory
[-] Change Mod to 0644
chmod: cannot access '/etc/selinux/arc/policy/policy.30': No such file or directory
[*] Change Context to u:object_r:cros_selinux_config_file:s0
chcon: cannot access '/etc/selinux/arc/policy/policy.30': No such file or directory
[!] Set Permissions and Context from
[-] /usr/local/crosswork/fin/sepolicy to /usr/local/crosswork/fin/sepolicy.magisk
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
[*] Change Owner:Group to :
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
chown: cannot access '/usr/local/crosswork/fin/sepolicy.magisk': No such file or directory
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
[-] Change Mod to 
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
chmod: missing operand after '/usr/local/crosswork/fin/sepolicy.magisk'
Try 'chmod --help' for more information.
stat: cannot statx '/usr/local/crosswork/fin/sepolicy': No such file or directory
[*] Change Context to 
chcon: failed to get security context of '/usr/local/crosswork/fin/sepolicy': No such file or directory
mv: cannot stat '/usr/local/crosswork/fin/sepolicy.magisk': No such file or directory
[-] /opt/google/containers/android/system.raw.img Backup exists already
[-] Generating SquashFS with Magisk
rm: cannot remove '/opt/google/containers/android/system.raw.img': No such file or directory
Parallel mksquashfs: Using 4 processors
Creating 4.0 filesystem on /opt/google/containers/android/system.raw.img, block size 131072.
[========================================================================================================-] 79/79 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
        compressed data, compressed metadata, compressed fragments,
        compressed xattrs, compressed ids
        4k unaligned
        duplicates are removed
Filesystem size 2780.61 Kbytes (2.72 Mbytes)
        30.73% of uncompressed filesystem size (9047.11 Kbytes)
Inode table size 487 bytes (0.48 Kbytes)
        34.49% of uncompressed inode table size (1412 bytes)
Directory table size 249 bytes (0.24 Kbytes)
        61.94% of uncompressed directory table size (402 bytes)
Xattr table size 45 bytes (0.04 Kbytes)
        100.00% of uncompressed xattr table size (45 bytes)
Number of duplicate files found 3
Number of inodes 23
Number of files 13
Number of fragments 2
Number of symbolic links  5
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 5
Number of ids (unique uids + gids) 3
Number of uids 2
        unknown (755)
        root (0)
Number of gids 2
        unknown (777)
        root (0)
[*] Set Magisk SquashFS System
[*] Change Context to u:object_r:cros_system_file:s0
[*] cleaning up /usr/local/crosswork/fin

**Comment by windowz414** [comment]
@1457384613gh

I think some update to CROS changed SEL context labels, which is causing this issue. You need to work around this by looking into rootAVD and patching its script while fiddling around the ARC++ container.

**Comment by 1457384613gh** [comment]
So this script is used for ARCVM ?

Give me an older version for ARC++ before, please!
Thank you!

**Comment by 1457384613gh** [comment]
Could you release a .zip file for ARC++ ?

And codes here are used for ARCVM.

**Comment by windowz414** [comment]
> So this script is used for ARCVM ?

ARCVM is the name of ARC after Android 11.

> Give me an older version for ARC++ before, please! Thank you!

Unfortunately, ARC builds are done per-device/board basis and one implementation doesn't work on other.

> Could you release a .zip file for ARC++ ?

Well, all devices with Android 9 ARC have ARC++.

> And codes here are used for ARCVM.

Again, ARCVM is for Android 11, and I remember this script was unable to be used for it at all.

**Comment by 1457384613gh** [comment]
OK，got it, my Fairy Goddess.
Your Highness.

**Comment by 1457384613gh** [comment]
https://fydeos.io/download/

Could you help to adapt the script for FydeOS?
It is a fork of chromiumOS

This fork runs faster than Brunch patches.

And the first image supports Core 1st Gen.

It could boot on my old Dell E5510 with Core i5 M450, and  Android Container runs faster than waydroid on Manjaro.

It could really save many old devices.

**Comment by windowz414** [comment]
> https://fydeos.io/download/
> 
> Could you help to adapt for FydeOS, fork of chromiumOS？

I'll try it on my laptop or 2in1 first, it's hard to do it remotely.

But if you want to, we can switch to emails or a messaging platform of your choice and that I have to do it together.

**Comment by 1457384613gh** [comment]
https://github.com/openFyde

OK, I am going to find several friends from forums to give us help.

**Comment by 1457384613gh** [comment]
Before installation, you could boot .img by Ventoy instead of firing a USB flash disk.

**Comment by windowz414** [comment]
> Before installation, you could boot .img by Ventoy instead of firing a USB flash disk.

Thanks for the info!

**Comment by 1457384613gh** [comment]
My pleasure, Your Highness.

**Comment by 1457384613gh** [comment]
I've found that /system is mounted as overlayfs.

I wonder whether there is way not to edit system.raw.img, just to make full use of Overlayfs.

**Comment by windowz414** [comment]
> I've found that /system is mounted as overlayfs.
> 
> I wonder whether there is way not to edit system.raw.img, just to make full use of Overlayfs.

You can check the scripts about that. I'm sure you should be able to edit the images easily after mounting.
