### ISSUE TITLE
Support Kernel-SU for ARCVM

### ISSUE THREAD

**Issue by 1457384613gh** [newbit1/rootCROS#7]
Hi, I've seen `vmlinux` `system.raw.img` `vendor.raw.img` into `ROOT-A: /opt/google/vms/android`.

Maybe, we could patch `vmlinux` to support [Kernel-SU](https://github.com/tiann/KernelSU).

Put a fake `boot.img` next `vmlinux`.
Patch `vmlinux` to mount fake `boot.img`.

**Comment by djfaizp** [comment]
Following it, may be we need to patch kernel with kernel su patch

**Comment by windowz414** [comment]
Well, we need to recompile the kernel for that, as patching kernel binary is often hard. Thankfully ARCVM kernel is open source on Google's source code storages.

**Comment by 1457384613gh** [comment]
https://github.com/M-L-P/brunch-grub2
[vmlinux.zip](https://github.com/newbit1/rootCROS/files/11766812/vmlinux.zip)


![Screenshot 2023-06-16 13 24 15](https://github.com/newbit1/rootCROS/assets/69227436/b5429cbd-2394-4ded-83d4-f85a739ed63c)
![Screenshot 2023-06-16 13 27 06](https://github.com/newbit1/rootCROS/assets/69227436/50186c9d-20c3-40e7-b18e-7de681696873)

**Comment by djfaizp** [comment]
> https://github.com/M-L-P/brunch-grub2 [vmlinux.zip](https://github.com/newbit1/rootCROS/files/11766812/vmlinux.zip)
> 
> ![Screenshot 2023-06-16 13 24 15](https://user-images.githubusercontent.com/69227436/246330677-b5429cbd-2394-4ded-83d4-f85a739ed63c.png) ![Screenshot 2023-06-16 13 27 06](https://user-images.githubusercontent.com/69227436/246330684-50186c9d-20c3-40e7-b18e-7de681696873.png)

could you please tell me how do you compile it ? i have ryzen 5 3600 build

**Comment by 1457384613gh** [comment]
crosh
`shell`
`cd /opt/google/vms/android`
`ls -l`
`sudo mv vmlinux vmlinux.bak`
`ls -l`
`cd ~/Downloads`
`ls -l`
`sudo cp vmlinux /opt/google/vms/android`
`cd /opt/google/vms/android`
`ls -l`
`sudo reboot`

**Comment by djfaizp** [comment]
> crosh `shell` `cd /opt/google/vms/android` `ls -l` `sudo mv vmlinux vmlinux.bak` `ls -l` `cd ~/Downloads` `ls -l` `sudo cp vmlinux /opt/google/vms/android` `cd /opt/google/vms/android` `ls -l` `sudo reboot`

Thank you very much i was looking for it since long time can you share telegram i want to discuss regarding making kernel for ryzen 5 3600 as there is no cgpu so i have to use Nvedia 1660 graphics cards and it will may not support this kernel

**Comment by 1457384613gh** [comment]
My phone number is banned.
I cannot login.

**Comment by 1457384613gh** [comment]
Download vmlinux.zip, and try it.

It is not the kernel of the host system.

It is the kernel of ARCVM.

**Comment by djfaizp** [comment]
![Uploading Screenshot 2023-06-16 7.55.15 PM.png…]()
![Screenshot 2023-06-16 7 51 32 PM](https://github.com/newbit1/rootCROS/assets/20996246/7fab538e-0c65-42de-906b-dd8259be0f18)
some apps not having any permission so can't open it they don't even have network permission to app

**Comment by 1457384613gh** [comment]
WiFi or Ethernet?

**Comment by djfaizp** [comment]
No issue with chrome os but only issue to some android apps force close ,internet issue ,It seems like kernel issue as i switch to default everything works fine now
